# (PART) Intro to jamovi {.unnumbered}

# 3. Overview of jamovi

jamovi is a free and open statistical software that helps us run our descriptive and inferential statistics. Why are we using jamovi and not another program?

1.  Did I mention it's free? You won't ever have to pay a dime to use the software in the future.

2.  It's open source, meaning that the statistical community helps support and improve the program. As jamovi says, "jamovi is made by the scientific community, for the scientific community."

3.  It's built on top of the R statistical language, meaning you can begin learning how to code (if you want). I do all of my statistical analyses using R in a different program called RStudio (actually this book was developed in RStudio and hosted on GitHub!). It's a very powerful tool which is also free and open source.

4.  It's incredibly easy to learn and use. I have taught statistics using both SPSS and jamovi, and students greatly prefer jamovi.

5.  It promotes reproducibility. jamovi will save your data, analyses, options, and results all in one file so you can easily pick up where you left off. This will make your homework and future data analyses a breeze.

### Additional jamovi videos and resources {.unlisted .unnumbered}

Here are some additional resources on jamovi I recommend you bookmark and use when you are struggling or need additional support:

-   [jamovi 2022 tutorials](https://www.youtube.com/playlist?list=PLvYqRUmlLZUMJ0EUxuTAA1f407wmBQ1QX) by Alexander Swan on YouTube

-   [jamovi docs](https://docs.jamovi.org/) provide more support for using jamovi, including tips for transitioning from SPSS to jamovi and from jamovi to R

-   caution: these use an older version of jamovi! [Introduction to jamovi LinkedIn Learning course](https://www.linkedin.com/learning/introduction-to-jamovi/) by Barton Poulson, founder of [datalab.cc](https://datalab.cc/jamovi/) (you can find the video on YouTube and other places now, too, if you do not have LinkedIn Learning)

### Navigating the jamovi interface {.unlisted .unnumbered}

I recommend you watch this video by Alexander Swan on [navigating the jamovi interface in jamovi](https://youtu.be/t0tQcs-E5Z4) to understand everything. Note that he is using a Mac in his demonstrations and that he has downloaded a ton of add-on modules which is why his Analyses tab looks different from yours.

### Opening data in jamovi {.unlisted .unnumbered}

I recommend you watch this video by Alexander Swan on [opening files in jamovi](https://youtu.be/nB85VyskK08).

I occasionally get questions on how to open .sav files (SPSS files) in jamovi. Here's a video walking you through that.

```{r echo = FALSE, message = FALSE, warning = FALSE}
library(vembedr)
embed_url("https://www.youtube.com/watch?v=e-09OfLVs2U")
```

### Entering data in jamovi {.unlisted .unnumbered}

Occasionally you need to manually enter data into jamovi instead of opening a pre-existing data file. I recommend you watch this video by Alexander Swan on [entering data manually in jamovi](https://youtu.be/g3a2hGwNZ7o).

### Annotating output in jamovi {.unlisted .unnumbered}

Sometimes I may ask you to submit a file of your output with annotations. I recommend you watch this video by Alexander Swan on [annotating output in jamovi](https://youtu.be/I6SZtH__ICA).
