# 8. Writing up results

This chapter goes over how to write up statistical results. Refer back to this chapter often!

### The 4 components of writing statistical results {.unlisted .unnumbered}

When writing up the results of a statistical test, we should always include the following information:

1.  Description of your research question and/or hypotheses.

2.  Description of your data. If you fail to meet assumptions, you should specify that and describe what test you chose to perform as a result.

3.  The results of the inferential test, including what test was performed, the test value and degrees of freedom, p-value, and effect size.

4.  Interpretation of the results or whether the hypothesis was supported or not, including any other information as needed.

### An example {.unlisted .unnumbered}

Let's go through an example. This data comes from the independent t-test chapter. Here's the four pieces of information we need to know:

1.  **Research question or hypothesis**: Is there a difference in student grades between Anastasia's and Bernadette's classes?
2.  **Descriptive statistics**: Anastasia's students (*M* = 74.53, *SD* = 9.00, *n* = 15); Bernadette's students (*M* = 69.06, *SD* = 5.77, *n* = 18)
3.  **Inferential statistics**: *t* (31) = 2.12, *p* = .043, *d* = .74
4.  **Interpretation of results that answer's the research question or demonstrates whether the hypothesis was rejected or not**: Anastasia's students had significantly higher grades than Bernadette's students.

Given the results of the t-test, we can write up our results in APA something like this:

> The research question was whether there was a difference in student grades between Anastasia's and Bernadette's classes. Anastasia's students (*M* = 74.53, *SD* = 9.00, *n* = 15) had significantly higher grades than Bernadette's students (*M* = 69.06, *SD* = 5.77, *n* = 18), *t* (31) = 2.12, *p* = .043, *d* = .74.

Let's compare that write-up against the 4 things we need to report:

> **#1:** The research question was whether there was a difference in student grades between Anastasia's and Bernadette's classes. **#4** Anastasia's students **#2** (*M* = 74.53, *SD* = 9.00, *n* = 15) **#4 cont.** had significantly higher grades than Bernadette's students **#2** (*M* = 69.06, *SD* = 5.77, *n* = 18), **#3** *t* (31) = 2.12, *p* = .043, *d* = .74.

Sometimes, people like to put the statistics inside a parentheses. In that case, you need to change the parentheses around the degrees of freedom as brackets. Here's another example write-up of the results in APA style:

> **#1** I tested the difference in grades between Anastasia's students **#2** (*M* = 74.53, *SD* = 9.00, *n* = 15) and Bernadette's students (*M* = 69.06, *SD* = 5.77, *n* = 18). **#3** An independent samples t-test showed that the 5.48 mean difference between the tutor's student was statistically significant (*t* [31] = 2.12, *p* = .043, *d* = .74). **#4** Therefore, we reject the null hypothesis that there is no difference in grades between the two classes.

Note that these are not the only way we can write up the results in APA format. The key is that we include all four pieces of information as specified above, that the information is correct, and that the information is presented in a logical order based on how we test hypotheses.

```{block, type="info"}

One tip I strongly recommend when writing up your results is to read out your results minus everything in parentheses to check for correct grammar. 
```

### 7 Common Errors {.unlisted .unnumbered}

The following video details 7 common errors that folks make when reporting statistical results:

1.  **Italics**: italicize all the statistical letters (e.g., M, SD, p, t, r, etc.) but not Greek letters
2.  **Decimal places**: round everything to 2 decimals except p-values which are rounded to 3 decimals
3.  **Leading zero**: no leading zeros for p-values, correlation, eta-squared, and betas, but leading zeros for everything else
4.  **p-values**: report exact p-values, and if values are less than .001 we report it as *p* \< .001 (never as *p* \<= .001!)
5.  **Parenthesis**: we cannot put a parenthesis inside a parenthesis; in those cases, put a bracket inside a parenthesis (e.g., here's a parentheses with [something] in brackets)
6.  ***N*** (populations or the full study sample) or ***n*** (samples, or a sub-sample within a study)
7.  **Blanks and F**: to aid readability, there is no space between the statistcal test and the parentheses for the degrees of freedom, but for the F-statistic there is a space between the two degrees of freedom, such as *F*(2, 126)

```{r echo = FALSE, message = FALSE, warning = FALSE}
library(vembedr)
embed_url("https://www.youtube.com/watch?v=rlZnbQUGhjc")
```
